# config.yaml

# Data paths
data_path: "Complete_data_Training.csv"
output_path: "predictions_output.csv"

# Model parameters
model_params:
  fold_strategy: "timeseries"
  train_size: 0.8
  random_state: 42

# Logging configuration
logging:
  level: "INFO"
  file_path: "logs/energy_predictor.log"

# Experiment tracking
mlflow:
  tracking_uri: "sqlite:///mlflow.db"
  experiment_name: "energy_predictions"